version: "3.9"

services:

  sql-ai:
    build: .
    container_name: sql-ai-assistant

    cpus: "2.5"
    mem_limit: 8g
    mem_reservation: 2g

    ports:
      - "8000:8000"

    volumes:
      - ./models:/models
      - ./vector_db:/vector_db

    networks:
      - internal_net

    restart: unless-stopped

networks:
  internal_net:
    driver: bridge
    internal: true